#!/usr/bin/env fish

set DOTFILES_DIR ~/dotfiles

# Copy the dotfiles from ~/.config to ~/dotfiles/.config
cp -r ~/.config/hypr $DOTFILES_DIR
cp -r ~/.config/waybar $DOTFILES_DIR
cp -r ~/.config/wlogout $DOTFILES_DIR
cp -r ~/.config/ghostty $DOTFILES_DIR
cp -r ~/.config/helix $DOTFILES_DIR
cp -r ~/.config/niri $DOTFILES_DIR
cp -r ~/.config/nvim $DOTFILES_DIR
cp -r ~/.vimrc $DOTFILES_DIR
cp -r ~/.config/tmux $DOTFILES_DIR
cp -r ~/.config/fuzzel $DOTFILES_DIR
cp -r ~/.config/kitty $DOTFILES_DIR
cp -r ~/.config/mako $DOTFILES_DIR
cp -r ~/Pictures/wallpaper $DOTFILES_DIR

echo "Dotfiles copied successfully to $DOTFILES_DIR!"
