[language-server.tailwindcss-ls]
command = "tailwindcss-language-server" 
args = ["--stdio"]
config = { userLanguages = { templ = "html", "*.templ" = "html"} }

[language-server.discord-rpc]
command = "discord-rpc-lsp"

[language-server.phpactor]
command = "phpactor"
args = ["language-server"]

[[language]]
name = "html"
language-servers = [
  "vscode-html-language-server",
  "tailwindcss-ls",
  "discord-rpc"
]
# formatter = { command = 'prettier', args = ["--parser", "html"] }
# auto-format = true

[[language]]
name = "css"
language-servers = [
  "vscode-css-language-server",
  "tailwindcss-ls",
  "discord-rpc"
]
# formatter = { command = 'prettier', args = ["--parser", "css"] }
# auto-format = true

[[language]]
name = "typescript"
language-servers = [
  "typescript-language-server",
  "discord-rpc"
]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "javascript"
language-servers = [
  "typescript-language-server",
  "discord-rpc"
]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
# auto-format = true

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }
auto-format = true

[[language]]
name = "jsx"
language-servers = [
  "typescript-language-server",
  "tailwindcss-ls",
  "discord-rpc"
]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
language-servers = [
  "typescript-language-server",
  "tailwindcss-ls",
  "discord-rpc"
]
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "svelte"
language-servers = [
  "svelteserver",
  "tailwindcss-ls",
  "discord-rpc"
]
auto-format = true

[[language]]
name = "c"
language-servers = ["clangd", "discord-rpc"]
formatter = { command = "clang-format" }
auto-format = true

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "discord-rpc"]
formatter = { command = "rustfmt" }
auto-format = true

[[language]]
name = "go"
language-servers = ["gopls", "discord-rpc"]
auto-format = true

[[language]]
name = "python"
language-servers = ["pyright", "discord-rpc"]

[[language]]
name = "php"
language-servers = ["phpactor",  "vscode-html-language-server"]
formatter = { command = "php-cs-fixer", args = ["fix", "--quiet", "--using-cache=no"] }
auto-format = false

[[language]]
name = "c-sharp"
formatter = { command = "dotnet", args = ["format", "--stdin"] }

[[language]]
name = "java"
formatter = { command = "google-java-format" }

[[language]]
name = "astro"
formatter = { command = "prettier", args = ["--parser", "astro"] }
language-servers = ["astro-ls", "discord-rpc"]

[[language]]
name = "templ"
language-servers = ["templ", "discord-rpc", "tailwindcss-ls"]
auto-format = true
